### ISSUE TITLE
the new version does not work

### ISSUE THREAD

**Issue by badgeminer** [Rabbitminers/Create-Mod-Addon-Template#1]

**Comment by Rabbitminers** [comment]
That's because this is a tool to generate templates. You can either use the legacy version from the `legacy` directory or what I would reccomend in the mean time is use one of these more up to date templates

https://github.com/Rabbitminers/Create-Multiloader-Addon-Template

https://github.com/Fabricators-of-create/Create-Multiloader-Addon-Template
